### ISSUE TITLE
Error when adding dummy 

### ISSUE THREAD

**Issue by DaveGraham123456** [rasod/homebridge-dummy-garage#6]
Attempting to load a setting.

Receive a "Error Failed to save config: Plugin Alias could not be determines"

see screen shot.

![image](https://user-images.githubusercontent.com/68233868/102880614-b9a4b480-449f-11eb-962b-76a1a114e98f.png)

**Comment by rasod** [comment]
Hmmm, which UI are you using?

**Comment by rasod** [comment]
Should be fixed in version 1.2.3

**Comment by DaveGraham123456** [comment]
Hey dude.  Nice quick work

I am using Homebridge UI v1.1.7 on Raspbian GNU/Linux Buster (10)

I updated, and still the same issue.  Do you want logs from anywhere?

**Comment by cstephenmaloy** [comment]
I was having the same issue I assumed my set up was wrong so I just ordered a hoobs box thinking it might be simpler, should this be easier to set up on hoobs? This is such an awesome plug-in I want to get working
